<?xml version="1.0"?><robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- <xacro:property name="width" value="0.1" /> -->
<!-- <xacro:property name="height1" value="2" /> -->
<link name="world"/>
<!-- <joint name="fixed" type="fixed"><parent link="world"/><child link="link1"/></joint><link name="link1"> -->
<!-- <visual><origin xyz="0 0 ${height1/2}" rpy="0 0 0"/><geometry><box size="${width} ${width} ${height1}"/></geometry></visual> -->
<!-- </link> -->
</robot>